# Site settings
title: Reactive Explorations
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Aleksandar Milošević. A lot of RxJava & RxJS samples, links and tutorials.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amilosevic.github.com" # the base hostname & protocol for your site
github_username:  amilosevic

gems:
  - jekyll-gist

# Build settings
markdown: kramdown

collections:
 tutorial:
  output: true
